<!DOCTYPE html><?php

$core = json_decode('{"core-ajax":"components/core-ajax/core-ajax.html","core-xhr":"components/core-ajax/core-xhr.html","core-animation-group":"components/core-animation/core-animation-group.html","core-animation":"components/core-animation/core-animation.html","core-collapse":"components/core-collapse/core-collapse.html","core-component-page":"components/core-component-page-dev/core-component-page.html","core-drag-drop":"components/core-drag-drop/core-drag-drop.html","core-drawer-panel":"components/core-drawer-panel/core-drawer-panel.html","core-field":"components/core-field/core-field.html","core-header-panel":"components/core-header-panel/core-header-panel.html","core-icon":"components/core-icon/core-icon.html","core-icon-button":"components/core-icon-button/core-icon-button.html","core-iconset":"components/core-iconset/core-iconset.html","core-iconset-svg":"components/core-iconset-svg/core-iconset-svg.html","core-input":"components/core-input/core-input.html","core-item":"components/core-item/core-item.html","core-list":"components/core-list/core-list.html","core-localstorage":"components/core-localstorage/core-localstorage.html","core-media-query":"components/core-media-query/core-media-query.html","core-menu":"components/core-menu/core-menu.html","core-submenu":"components/core-menu/core-submenu.html","core-menu-button":"components/core-menu-button/core-menu-button.html","core-meta":"components/core-meta/core-meta.html","core-overlay":"components/core-overlay/core-overlay.html","core-pages":"components/core-pages/core-pages.html","core-range":"components/core-range/core-range.html","core-scaffold":"components/core-scaffold/core-scaffold.html","core-scroll-header-panel":"components/core-scroll-header-panel/core-scroll-header-panel.html","core-selector":"components/core-selector/core-selector.html","core-shared-lib":"components/core-shared-lib/core-shared-lib.html","core-signals":"components/core-signals/core-signals.html","core-splitter":"components/core-splitter/core-splitter.html","core-toolbar":"components/core-toolbar/core-toolbar.html","core-tooltip":"components/core-tooltip/core-tooltip.html","core-transition":"components/core-transition/core-transition.html"}');
$paper = json_decode('{"paper-button":"components/paper-button/paper-button.html","paper-checkbox":"components/paper-checkbox/paper-checkbox.html","paper-dialog-transition":"components/paper-dialog/paper-dialog-transition.html","paper-dialog":"components/paper-dialog/paper-dialog.html","paper-fab":"components/paper-fab/paper-fab.html","paper-focusable":"components/paper-focusable/paper-focusable.html","paper-group":"components/paper-form/paper-form.html","paper-icon-button":"components/paper-icon-button/paper-icon-button.html","paper-input":"components/paper-input/paper-input.html","paper-item":"components/paper-item/paper-item.html","paper-menu-button-overlay":"components/paper-menu-button/paper-menu-button-overlay.html","paper-menu-button-overlay-container":"components/paper-menu-button/paper-menu-button.html","paper-progress":"components/paper-progress/paper-progress.html","paper-radio-button":"components/paper-radio-button/paper-radio-button.html","paper-radio-group":"components/paper-radio-group/paper-radio-group.html","paper-ripple":"components/paper-ripple/paper-ripple.html","paper-shadow":"components/paper-shadow/paper-shadow.html","paper-slider":"components/paper-slider/paper-slider.html","paper-tab":"components/paper-tabs/paper-tab.html","paper-tabs":"components/paper-tabs/paper-tabs.html","paper-toast":"components/paper-toast/paper-toast.html","paper-toggle-button":"components/paper-toggle-button/paper-toggle-button.html"}');

foreach ($core as $k=>$v) {
	exec("bower install Polymer/$k >/dev/null 2>&1");
	echo '<link rel="import" href="'.$v.'">';
}
foreach ($paper as $k=>$v) {
	exec("bower install Polymer/$k >/dev/null 2>&1");
        echo '<link rel="import" href="'.$v.'">';
}
